name: clearit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.3
#  not null safe
#  pin_entry_text_field: ^0.1.4
#  full_screen_image: ^1.0.2
#  modal_progress_hud: ^0.1.3

#  flutter_windowmanager: ^0.0.2

#  new
  flare_flutter: ^3.0.1
  firebase_storage: ^8.1.3
  shared_preferences: ^2.0.6
  flutter_staggered_animations: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  timer_count_down: ^2.2.0
  cached_network_image: ^3.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  fluttertoast: ^8.0.7
  argon_buttons_flutter: ^1.1.0
  stop_watch_timer: ^1.3.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  photo_view: ^0.11.1
  url_launcher: ^6.0.7
  flutter_pdfview: ^1.1.0
  audioplayers: ^0.19.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  country_pickers: ^2.0.0
  google_mobile_ads: ^0.13.4
  intl: ^0.17.0
  image_cropper: ^1.4.1
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^8.1.1+1
  image_picker: ^0.8.0+4
  file_picker: ^3.0.3
  flutter_windowmanager: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/
    - images/clearit/
    - images/arts/
    - images/dailyWord/
